export const projects = [
 {name:'Tetra Connect',image:'tetra.png',category:['Paiement · Application web','Payments · Web application'],description:['Piloter un parc de terminaux, à distance.','Managing a terminal fleet, remotely.'],detail:['Un portail destiné aux gestionnaires de parcs de terminaux TELIUM2 et TETRA. Il offre une vision précise du parc et permet de déclencher des opérations de maintenance à distance, en toute autonomie.','A portal for TELIUM2 and TETRA terminal fleet managers. It provides a detailed view of the fleet and enables independent remote maintenance operations.'],tags:['Angular','Node.js','PostgreSQL','Docker','Scalingo','GitLab CI/CD','Shell','Linux','JavaScript'],url:'https://tetra-connect.com/#/login',style:'tetra'},
 {name:'Regmate',image:'regmate.jpg',category:['RegTech · Application web','RegTech · Web application'],description:['La conformité, entièrement digitalisée.','Compliance, fully digitalised.'],detail:['Une solution de digitalisation des processus de conformité pour les institutions financières et les entreprises assujetties. Une application flexible, personnalisable et configurable selon les besoins de chaque organisation.','A solution that digitises compliance processes for financial institutions and regulated businesses. A flexible, customisable and configurable application tailored to each organisation.'],tags:['Angular','Node.js','Python','MongoDB','Apache','PM2','Gunicorn','Shell','Linux','JavaScript'],url:'https://www.regmate.lu/',style:'regmate'},
 {name:'Feelgood',image:'feelgood1.png',category:['Bien-être · Application mobile','Wellbeing · Mobile application'],description:['Rendre la thérapie plus accessible.','Making therapy more accessible.'],detail:['Une plateforme de thérapie en ligne conçue pour faciliter l’accès à un accompagnement psychologique. Elle permet aux personnes qui préfèrent rester chez elles ou ne peuvent pas se déplacer de consulter à distance.','An online therapy platform designed to improve access to psychological support. It enables people who prefer staying at home or cannot travel to access therapy remotely.'],tags:['Ionic','Angular','Node.js','Firebase','Google Cloud','Python','Java','JavaScript','Google Play Store'],url:'https://play.google.com/store/apps/details?id=com.ifeelgood.feelgood',style:'feelgood'}
];
export const skills = [
 {icon:"Code2",title:['Langages','Languages'],items:['JavaScript','Python','Java','Shell scripting']},
 {icon:"Layers3",title:['Développement web','Web development'],items:['Angular','Node.js','Express.js','Flask','Spring Boot']},
 {icon:"Database",title:['Bases de données','Databases'],items:['SQL','PostgreSQL','NoSQL','MongoDB','Elasticsearch']},
 {icon:"Terminal",title:['Cloud & déploiement','Cloud & deployment'],items:['Google Cloud','Docker','Scalingo','Apache','PM2','SSL','Gunicorn','Linux']},
 {icon:"ScanLine",title:['Extraction de données','Data extraction'],items:['Scraping','Crawling','OCR']},
 {icon:"Workflow",title:['Méthodes & qualité','Methods & quality'],items:['Scrum','UML','TDD','DevOps','GitLab CI/CD','SonarQube']}
];
export const jobs = [
 {company:'Ingenico',role:['Développeur Full Stack','Full Stack Developer'],place:'Suresnes, France',date:['Oct. 2022 — présent','Oct 2022 — present'],text:['Développement frontend et backend, intégration de SonarQube dans GitLab CI/CD, déploiement des versions de test, préparation de requêtes SQL et maintenance applicative.','Frontend and backend development, SonarQube integration into GitLab CI/CD, test deployments, SQL queries and application maintenance.'],stack:'JavaScript · Node.js · Angular · Docker · Scalingo · PostgreSQL · Git · GitLab CI/CD · SonarQube · Linux'},
 {company:'Novencia',role:['Consultant Full Stack','Full Stack Consultant'],place:'Paris, France',date:['Août 2022 — présent','Aug 2022 — present'],text:['Consultant Full Stack sur un environnement JavaScript, Node.js, Angular, Docker, Python, Java et bases de données SQL et NoSQL.','Full Stack consulting across JavaScript, Node.js, Angular, Docker, Python, Java, and SQL and NoSQL databases.'],stack:'JavaScript · Node.js · Angular · Docker · Python · Java · SQL · NoSQL · MongoDB · PostgreSQL'},
 {company:'Equalios',role:['Développeur Full Stack','Full Stack Developer'],place:'Tunis, Tunisie',date:['Jan. 2020 — juil. 2022','Jan 2020 — Jul 2022'],text:['Conception et développement de Feelgood et Regmate, architecture multi-tenant, extraction de données par OCR et communication entre applications. Configuration des environnements et serveurs, livraisons en production, maintenance OVH et sécurisation par pare-feu.','Design and development of Feelgood and Regmate, multi-tenant architecture, OCR data extraction and inter-application communication. Environment and server configuration, production releases, OVH maintenance and firewall security.'],stack:'JavaScript · Node.js · Angular · Python 3 · MongoDB · Elasticsearch · Google Cloud · Apache · PM2 · SSL · Shell · Linux'},
 {company:'SparkIt',role:['Développeur Full Stack · temps partiel','Full Stack Developer · part-time'],place:'Tunis, Tunisie',date:['Sept. — nov. 2019','Sep — Nov 2019'],text:['Conception et réalisation d’un ERP, modélisation UML, participation aux réunions de planification et traduction des besoins métier en fonctionnalités.','Design and implementation of an ERP, UML modelling, planning meetings and translating business requirements into functionality.'],stack:'Java 8 · Spring Boot · Angular 7 · Angular Material · PostgreSQL'}
];
